# Site settings
title: Gage Henrich | GitHub
description: "let's solve problems with code"
url: "https://gagehenrich.github.io"  # replace with your actual GitHub Pages URL

# Google 
google_verify: google14d8fa5af2a5c056.html
